spring:
    cloud:
        stream:
            bindings:
                outputChannel:
                   destination: stringBroadcast
                   binder: kafka
                   group: stringProducer

server:
  port: 8080